# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
default:
  image: eclipse-temurin:17.0.8.1_1-jre

stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

unit-test:
  stage: test
  script:
    - gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml