# The amount of claims a player is allowed to create.
claim_limit: 3

# The amount of blocks a player's claims are allowed to occupy.
claim_block_limit: 5000

# The initial size of the claim that is created in a square. (Minimum value of 3)
initial_claim_size: 7

# The minimum size that a claim is allowed to occupy. (Minimum value of 3)
minimum_partition_size: 3

# The minimum distance there is allowed to be between claims.
distance_between_claims: 1

# The amount of time in seconds it takes for the visualiser to disappear when the claim tool is unequipped.
visualiser_hide_delay_period: 2

# The minimum amount of time in seconds the visualiser is allowed to be refreshed to prevent spam.
visualiser_refresh_period: 1

# The language of text elements.
# EN - Original
# add more <?>.properties files in the override folder to
plugin_language: EN

# The id value for resource packs that change the model of the claim tool.
custom_claim_tool_model_id: 732000

# The id value for resource packs that change the model of the move tool.
custom_move_tool_model_id: 732001