name: Build Gradle

on:
  push:
    branches:
      - main
      - staging
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Gradle using shadowJar
      run: ./gradlew shadowJar

    - name: Save Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build/libs/
