name: Unit Test Gradle

on:
  push:
    branches:
      - main
      - staging
      - release/*
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Test with Gradle
      run: ./gradlew test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
